# -*- coding: utf-8 -*-
"""Capstone Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NA7XraPD3cfrPXv4QpmN-D3xxIcqGxEV
"""

#This is mainly used for capstone project

import pandas as pd
import numpy as np

print('Hello Capstone Project Course!')

